# Generated by Django 4.2.6 on 2024-05-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(default=dict),
        ),
    ]
