# Generated by Django 4.2.6 on 2024-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_billing_address_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
