# Generated by Django 4.2.6 on 2024-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
