# Generated by Django 4.2.6 on 2024-07-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_league_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
