# Generated by Django 4.2.6 on 2024-02-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_league_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
