# Generated by Django 4.2.6 on 2024-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_team_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image_url',
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
