# Generated by Django 4.2.6 on 2024-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_team_image_url_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='image_url',
        ),
        migrations.AddField(
            model_name='league',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
