# Generated by Django 4.2.6 on 2024-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_category_image_alter_league_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='max_available_size',
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
