# Generated by Django 4.2.6 on 2024-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_address_orderdetails_order_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_available_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', 'Extra Large'), ('3XL', 'Extra Large'), ('4XL', 'Extra Large')], default='2XL', max_length=3),
        ),
    ]
